#include "site_config.hpp"
#include <fstream>
#include <sstream>
#include <iostream>
#include <algorithm>
#include <map>
#include <mutex>
#include <shared_mutex>

// Global instance
SiteConfig site_config;

// ─────────────────────────────────────────────────────────────
static std::string trim(const std::string& s)
{
    auto b = s.find_first_not_of(" \t\r\n");
    auto e = s.find_last_not_of(" \t\r\n");
    return (b == std::string::npos) ? "" : s.substr(b, e - b + 1);
}

// ─────────────────────────────────────────────────────────────
void SiteConfig::load(const std::string& file_path)
{
    std::ifstream f(file_path);
    if (!f.is_open())
    {
        std::cerr << "[SiteConfig] Cannot open " << file_path << "\n";
        return;
    }

    // Temporary accumulator: domain -> field -> value
    std::map<std::string, std::map<std::string, std::string>> raw;
    // domain -> db_index -> field -> value
    std::map<std::string, std::map<int, std::map<std::string, std::string>>> raw_dbs;

    std::string line;
    while (std::getline(f, line))
    {
        line = trim(line);
        if (line.empty() || line[0] == '#') continue;

        auto eq = line.find('=');
        if (eq == std::string::npos) continue;

        std::string key = trim(line.substr(0, eq));
        std::string val = trim(line.substr(eq + 1));

        // Expected key pattern: site.<domain>.<field>
        //                    or site.<domain>.db.<N>.<field>
        if (key.rfind("site.", 0) != 0) continue;
        std::string rest = key.substr(5); // strip "site."

        // Find first dot after domain name
        auto d1 = rest.find('.');
        if (d1 == std::string::npos) continue;
        std::string domain = rest.substr(0, d1);
        std::string remainder = rest.substr(d1 + 1);

        if (remainder.rfind("db.", 0) == 0)
        {
            // site.<domain>.db.<N>.<field>
            std::string db_rest = remainder.substr(3); // strip "db."
            auto d2 = db_rest.find('.');
            if (d2 == std::string::npos) continue;
            int idx = std::stoi(db_rest.substr(0, d2));
            std::string db_field = db_rest.substr(d2 + 1);
            raw_dbs[domain][idx][db_field] = val;
        }
        else
        {
            raw[domain][remainder] = val;
        }
    }

    // Build SiteEntry list
    std::vector<SiteEntry> new_sites;
    for (auto& [domain, fields] : raw)
    {
        SiteEntry s;
        s.domain = domain;
        if (fields.count("fe_folder")) s.fe_folder = fields["fe_folder"];
        if (fields.count("be_folder")) s.be_folder = fields["be_folder"];
        if (fields.count("user"))      s.user      = fields["user"];
        if (fields.count("domain"))    s.domain    = fields["domain"];
        if (fields.count("be_type"))   s.be_type   = fields["be_type"];
        if (fields.count("run_cmd"))   s.run_cmd   = fields["run_cmd"];
        if (fields.count("be_port"))   s.be_port   = std::stoi(fields["be_port"]);
        if (fields.count("fe_build"))  s.fe_build  = fields["fe_build"];

        // Attach DB entries
        if (raw_dbs.count(domain))
        {
            for (auto& [idx, db_fields] : raw_dbs[domain])
            {
                DbEntry db;
                if (db_fields.count("name"))    db.alias   = db_fields["name"];
                if (db_fields.count("type"))    db.type    = db_fields["type"];
                if (db_fields.count("db_name")) db.db_name = db_fields["db_name"];
                s.dbs.push_back(db);
            }
        }

        new_sites.push_back(std::move(s));
    }

    {
        std::unique_lock lock(mutex_);
        sites_ = std::move(new_sites);
    }
    std::cout << "[SiteConfig] Loaded " << sites_.size() << " site(s) from " << file_path << "\n";
}

// ─────────────────────────────────────────────────────────────
std::vector<SiteEntry> SiteConfig::sites() const
{
    std::shared_lock lock(mutex_);
    return sites_;
}

// ─────────────────────────────────────────────────────────────
bool SiteConfig::findSite(const std::string& domain, SiteEntry& out) const
{
    std::shared_lock lock(mutex_);
    for (const auto& s : sites_)
    {
        if (s.domain == domain) { out = s; return true; }
    }
    return false;
}

// ─────────────────────────────────────────────────────────────
void SiteConfig::writeSite(const std::string& file_path, const SiteEntry& site)
{
    // Append new site block to the file
    std::ofstream f(file_path, std::ios::app);
    if (!f.is_open())
    {
        std::cerr << "[SiteConfig] Cannot write to " << file_path << "\n";
        return;
    }

    f << "\n# Auto-generated by server\n";
    f << "site." << site.domain << ".fe_folder=" << site.fe_folder << "\n";
    f << "site." << site.domain << ".be_folder=" << site.be_folder << "\n";
    f << "site." << site.domain << ".user="      << site.user      << "\n";
    f << "site." << site.domain << ".domain="    << site.domain    << "\n";
    f << "site." << site.domain << ".be_type="   << site.be_type   << "\n";
    f << "site." << site.domain << ".run_cmd="   << site.run_cmd   << "\n";
    f << "site." << site.domain << ".be_port="   << site.be_port   << "\n";
    f << "site." << site.domain << ".fe_build="  << site.fe_build  << "\n";
    f << "site." << site.domain << ".db_count="  << site.dbs.size()<< "\n";

    for (std::size_t i = 0; i < site.dbs.size(); ++i)
    {
        const auto& db = site.dbs[i];
        f << "site." << site.domain << ".db." << i << ".name="    << db.alias   << "\n";
        f << "site." << site.domain << ".db." << i << ".type="    << db.type    << "\n";
        f << "site." << site.domain << ".db." << i << ".db_name=" << db.db_name << "\n";
    }

    // Update in-memory list
    std::unique_lock lock(mutex_);
    bool found = false;
    for (auto& s : sites_)
    {
        if (s.domain == site.domain) { s = site; found = true; break; }
    }
    if (!found) sites_.push_back(site);
}
